create table demo (id integer primary key autoincrement, name varchar(20), phone varchar(20));

insert into demo (name, phone) values ('01', '01');
insert into demo (name, phone) values ('02', '02');
insert into demo (name, phone) values ('03', '03');
insert into demo (name, phone) values ('04', '04');
insert into demo (name, phone) values ('05', '05');
insert into demo (name, phone) values ('06', '06');
insert into demo (name, phone) values ('07', '07');
insert into demo (name, phone) values ('08', '08');
insert into demo (name, phone) values ('09', '09');
insert into demo (name, phone) values ('10', '10');
insert into demo (name, phone) values ('11', '11');
insert into demo (name, phone) values ('12', '12');
insert into demo (name, phone) values ('13', '13');
insert into demo (name, phone) values ('14', '14');
insert into demo (name, phone) values ('15', '15');
insert into demo (name, phone) values ('16', '16');
insert into demo (name, phone) values ('17', '17');
insert into demo (name, phone) values ('18', '18');
insert into demo (name, phone) values ('19', '19');
insert into demo (name, phone) values ('20', '20');
